// src/surveys/AnxietyScale/questions.js

const questions = [
  { id: "as1",  text: "Şu anda sakinim",                         options: [1,2,3,4], scoring: "reverse" },
  { id: "as2",  text: "Kendimi emniyette hissediyorum",          options: [1,2,3,4], scoring: "reverse" },
  { id: "as3",  text: "Şu anda sinirlerim gergin",               options: [1,2,3,4], scoring: "direct" },
  { id: "as4",  text: "Pişmanlık duygusu içindeyim",             options: [1,2,3,4], scoring: "direct" },
  { id: "as5",  text: "Şu anda huzur içindeyim",                 options: [1,2,3,4], scoring: "reverse" },
  { id: "as6",  text: "Şu anda hiç keyfim yok",                   options: [1,2,3,4], scoring: "direct" },
  { id: "as7",  text: "Başıma geleceklerden endişe ediyorum",     options: [1,2,3,4], scoring: "direct" },
  { id: "as8",  text: "Kendimi dinlenmiş hissediyorum",           options: [1,2,3,4], scoring: "reverse" },
  { id: "as9",  text: "Şu anda kaygılıyım",                       options: [1,2,3,4], scoring: "direct" },
  { id: "as10", text: "Kendimi rahat hissediyorum",               options: [1,2,3,4], scoring: "reverse" },
  { id: "as11", text: "Kendime güvenim var",                      options: [1,2,3,4], scoring: "reverse" },
  { id: "as12", text: "Şu anda asabım bozuk",                     options: [1,2,3,4], scoring: "direct" },
  { id: "as13", text: "Çok sinirliyim",                           options: [1,2,3,4], scoring: "direct" },
  { id: "as14", text: "Sinirlerimin çok gergin olduğunu hissediyorum", options: [1,2,3,4], scoring: "direct" },
  { id: "as15", text: "Kendimi rahatlamış hissediyorum",          options: [1,2,3,4], scoring: "reverse" },
  { id: "as16", text: "Şu anda halimden memnunum",                options: [1,2,3,4], scoring: "reverse" },
  { id: "as17", text: "Şu anda endişeliyim",                      options: [1,2,3,4], scoring: "direct" },
  { id: "as18", text: "Heyecandan kendimi şaşkına dönmüş hissediyorum", options: [1,2,3,4], scoring: "direct" },
  { id: "as19", text: "Şu anda sevinçliyim",                      options: [1,2,3,4], scoring: "reverse" },
  { id: "as20", text: "Şu anda keyfim yerinde.",                  options: [1,2,3,4], scoring: "reverse" },

  { id: "as21", text: "Genellikle keyfim yerindedir",             options: [1,2,3,4], scoring: "reverse" },
  { id: "as22", text: "Genellikle çabuk yorulurum",               options: [1,2,3,4], scoring: "direct" },
  { id: "as23", text: "Genellikle kolay ağlarım",                 options: [1,2,3,4], scoring: "direct" },
  { id: "as24", text: "Başkaları kadar mutlu olmak isterim",       options: [1,2,3,4], scoring: "direct" },
  { id: "as25", text: "Çabuk karar veremediğim için fırsatları kaçırırım", options: [1,2,3,4], scoring: "direct" },
  { id: "as26", text: "Kendimi dinlenmiş hissediyorum",           options: [1,2,3,4], scoring: "reverse" },
  { id: "as27", text: "Genellikle sakin, kendine hakim ve soğukkanlıyım", options: [1,2,3,4], scoring: "reverse" },
  { id: "as28", text: "Güçlüklerin yenemeyeceğim kadar biriktiğini hissederim", options: [1,2,3,4], scoring: "direct" },
  { id: "as29", text: "Önemsiz şeyler hakkında endişelenirim",     options: [1,2,3,4], scoring: "direct" },
  { id: "as30", text: "Genellikle mutluyum",                       options: [1,2,3,4], scoring: "reverse" },
  { id: "as31", text: "Herşeyi ciddiye alır ve endişelenirim",     options: [1,2,3,4], scoring: "direct" },
  { id: "as32", text: "Genellikle kendime güvenim yoktur",        options: [1,2,3,4], scoring: "direct" },
  { id: "as33", text: "Genellikle kendimi emniyette hissederim",   options: [1,2,3,4], scoring: "reverse" },
  { id: "as34", text: "Sıkıntılı ve güç durumlarla karşılaşmaktan kaçınırım", options: [1,2,3,4], scoring: "direct" },
  { id: "as35", text: "Genellikle kendimi hüzünlü hissederim",     options: [1,2,3,4], scoring: "direct" },
  { id: "as36", text: "Genellikle hayatımdan memnunum",            options: [1,2,3,4], scoring: "reverse" },
  { id: "as37", text: "Olur olmaz düşünceler beni rahatsız eder",  options: [1,2,3,4], scoring: "direct" },
  { id: "as38", text: "Hayal kırıklıklarını öylesine ciddiye alırım ki hiç unutamam", options: [1,2,3,4], scoring: "direct" },
  { id: "as39", text: "Aklı başında ve kararlı bir insanım",        options: [1,2,3,4], scoring: "reverse" },
  { id: "as40", text: "Son zamanlarda kafama takılan konular beni tedirgin ediyor", options: [1,2,3,4], scoring: "direct" },
];

export default questions;
