const questions = [
  { id: "eis1", text: "Kişisel sorunlarımı başkaları ile ne zaman paylaşacağımı bilirim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis2", text: "Bir sorunla karşılaştığım zaman benzer durumları hatırlar ve üstesinden gelebilirim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis3", text: "Genellikle yeni bir şey denerken başarısız olacağımı düşünürüm.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis4", text: "Bir sorunu çözmeye çalışırken ruh halimden etkilenmem.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis5", text: "Diğer insanlar bana kolaylıkla güvenirler.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis6", text: "Diğer insanların beden dili, yüz ifadesi gibi sözel olmayan mesajlarını anlamakta zorlanırım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis7", text: "Yaşamımdaki bazı önemli olaylar neyin önemli neyin önemsiz olduğunu yeniden değerlendirmeme yol açtı.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis8", text: "Bazen konuştuğum kimsenin ciddi mi olduğunu yoksa şaka mı yaptığını anlayamam.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis9", text: "Ruh halim değiştiğinde yeni olasılıkları görürüm.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis10", text: "Duygularımın yaşam kalitem üzerinde etkisi yoktur.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis11", text: "Hissettiğim duyguların farkında olurum.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis12", text: "Genellikle iyi şeyler olmasını beklemem.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis13", text: "Bir sorunu çözmeye çalışırken mümkün olduğunca duygusallıktan kaçınırım.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis14", text: "Duygularımı gizli tutmayı tercih ederim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis15", text: "Güzel duygular hissettiğimde bunu nasıl sonlandıracağımı bilirim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis16", text: "Başkalarının hoşlanabileceği etkinlikler düzenleyebilirim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis17", text: "Sosyal yaşamda neler olup bittiğini sıklıkla yanlış anlarım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis18", text: "Beni mutlu edecek uğraşılar bulmaya çalışırım.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis19", text: "Başkalarına gönderdiğim beden dili, yüz ifadesi gibi sözsüz mesajların farkındayımdır.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis20", text: "Başkaları üzerinde bıraktığım etkiyle pek ilgilenmem.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis21", text: "Ruh halim iyiyken sorunların üstesinden gelmek benim için daha kolaydır.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis22", text: "İnsanların yüz ifadelerini bazen doğru anlayamam.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis23", text: "Yeni fikirler üretmem gerektiğinde duygularım işimi kolaylaştırmaz.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis24", text: "Genellikle duygularımın niçin değiştiğini bilmem.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis25", text: "Ruh halimin iyi olması yeni fikirler üretmeme yardımcı olmaz.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis26", text: "Genellikle duygularımı kontrol etmekte zorlanırım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis27", text: "Hissettiğim duyguların farkındayımdır.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis28", text: "İnsanlar bana, benimle konuşmanın zor olduğunu söylerler.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis29", text: "Üstlendiğim görevlerden iyi sonuçlar alacağımı hayal ederek kendimi güdülerim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis30", text: "İyi bir şeyler yaptıklarında insanlara iltifat ederim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis31", text: "Diğer insanların gönderdiği sözel olmayan mesajların farkına varırım.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis32", text: "Bir kişi bana hayatındaki önemli bir olaydan bahsettiğinde ben de aynısını yaşamış gibi olurum.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis33", text: "Duygularımda ne zaman bir değişiklik olsa aklıma yeni fikirler gelir.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis34", text: "Sorunları çözüş biçimim üzerinde duygularımın etkisi yoktur.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis35", text: "Bir zorlukla karşılaştığım zaman umutsuzluğa kapılırım çünkü başarısız olacağıma inanırım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis36", text: "Diğer insanların kendilerini nasıl hissettiklerini sadece onlara bakarak anlayabilirim.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis37", text: "İnsanlar üzgünken onlara yardım ederek daha iyi hissetmelerini sağlarım.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis38", text: "İyimser olmak sorunlar ile baş etmeye devam edebilmem için bana yardımcı oluyor.", options: [1, 2, 3, 4, 5], scoring: "direct" },
  { id: "eis39", text: "Kişinin ses tonundan kendini nasıl hissettiğini anlamakta zorlanırım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis40", text: "İnsanların kendilerini neden iyi ya da kötü hissettiklerini anlamak benim için zordur.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
  { id: "eis41", text: "Yakın arkadaşlıklar kurmakta zorlanırım.", options: [1, 2, 3, 4, 5], scoring: "reverse" },
];

export default questions;
